import { z } from "zod";
import { platforms } from "./model";
const id = z.uuid(),
  text = z.string().trim().min(1).max(12000),
  short = z.string().trim().min(1).max(200),
  confirmed = z.literal(true);
export const controlCommand = z.discriminatedUnion("action", [
  z.object({ action: z.literal("distribution_process") }),
  z.object({
    action: z.literal("publication_record"),
    package_id: id,
    url: z.url().regex(/^https:\/\//),
    published_at: z.iso.datetime(),
    confirmed,
  }),
  z.object({
    action: z.literal("brand_save"),
    name: short,
    banned_patterns: z.array(z.string().min(1).max(500)).max(30).optional(),
    positioning: text,
    audience: text,
    pillars: z.array(short).min(1).max(10),
    tone: z.array(short).max(12),
    cta: short,
  }),
  z.object({ action: z.literal("brand_approve"), id, confirmed }),
  z.object({
    action: z.literal("idea_create"),
    title: short,
    source: z.enum([
      "story",
      "manual",
      "build",
      "audience",
      "competitor",
      "experiment",
      "analytics",
    ]),
    story_id: id.optional(),
    provenance: text,
    originality: z.string().max(2000).default(""),
  }),
  z.object({
    action: z.literal("idea_transition"),
    id,
    target: z.enum(["qualified", "selected", "archived"]),
  }),
  z.object({
    action: z.literal("content_create"),
    idea_id: id,
    platform: z.enum(platforms),
    format: z.enum(["video", "post", "thread", "carousel", "newsletter"]),
    purpose: text,
  }),
  z.object({
    action: z.literal("content_bind"),
    id,
    draft_id: id,
    production_id: id.optional(),
  }),
  z.object({
    action: z.literal("content_transition"),
    id,
    target: z.enum([
      "drafting",
      "draft_ready",
      "review",
      "approved",
      "rejected",
      "archived",
    ]),
    confirmed: z.boolean().default(false),
  }),
  z.object({
    action: z.literal("content_freshness"),
    id,
    evergreen: z.boolean(),
    fresh_until: z.iso.datetime().nullable(),
    confirmed,
  }),
  z.object({
    action: z.literal("claim_revalidate"),
    id,
    source_ids: z.array(id).min(1),
    notes: text,
    confirmed,
  }),
  z.object({
    action: z.literal("take_suggest"),
    text,
    topic: short,
    story_id: id.optional(),
    rationale: text,
    source_ids: z.array(id),
  }),
  z.object({
    action: z.literal("take_decide"),
    id,
    decision: z.enum(["approved", "rejected", "superseded"]),
    confirmed,
    reason: text,
  }),
  z.object({ action: z.literal("content_take"), id, take_id: id }),
  z.object({
    action: z.literal("story_reject"),
    story_id: id,
    reason: text,
    confirmed,
  }),
  z.object({
    action: z.literal("account_create"),
    platform: z.enum(platforms),
    handle: short,
  }),
  z.object({ action: z.literal("account_revoke"), id, confirmed }),
  z.object({
    action: z.literal("package_create"),
    id,
    privacy: z
      .enum([
        "PUBLIC_TO_EVERYONE",
        "MUTUAL_FOLLOW_FRIENDS",
        "FOLLOWER_OF_CREATOR",
        "SELF_ONLY",
        "public",
        "unlisted",
        "private",
      ])
      .optional(),
    caption: text,
    title: short,
    cta: z.string().max(300),
    thread: z.array(z.string().min(1).max(280)).max(25).default([]),
    graphic_ids: z.array(id).max(20).default([]),
  }),
  z.object({ action: z.literal("package_approve"), id, confirmed }),
  z.object({
    action: z.literal("content_final"),
    id,
    package_id: id,
    confirmed,
  }),
  z.object({
    action: z.literal("distribution_queue"),
    package_id: id,
    due_at: z.iso.datetime(),
    confirmed,
  }),
  z.object({
    action: z.literal("publication_demo"),
    package_id: id,
    confirmed,
  }),
  z.object({ action: z.literal("analytics_process") }),
  z.object({
    action: z.literal("metrics_record"),
    publication_id: id,
    metrics: z.record(z.string().regex(/^[a-z_]+$/), z.number().nonnegative()),
    raw: z.record(z.string(), z.unknown()),
    confirmed,
  }),
  z.object({ action: z.literal("performance_review"), id, notes: text }),
  z.object({
    action: z.literal("experiment_create"),
    name: short,
    hypothesis: text,
    arms: z.array(short).min(2).max(5),
    metric: short,
  }),
  z.object({
    action: z.literal("experiment_assign"),
    id,
    content_id: id,
    arm: short,
  }),
  z.object({
    action: z.literal("experiment_review"),
    id,
    notes: text,
    confirmed,
  }),
  z.object({
    action: z.literal("campaign_create"),
    name: short,
    content_ids: z.array(id).min(1).max(10),
  }),
  z.object({
    action: z.literal("newsletter_create"),
    title: short,
    package_ids: z.array(id).min(1).max(20),
    opening: z.string().max(5000),
  }),
  z.object({
    action: z.literal("newsletter_revise"),
    id,
    title: short,
    opening: z.string().max(5000),
  }),
  z.object({ action: z.literal("newsletter_review"), id }),
  z.object({ action: z.literal("newsletter_approve"), id, confirmed }),
  z.object({
    action: z.literal("graphic_queue"),
    content_id: id,
    template: z.enum([
      "source",
      "stat",
      "comparison",
      "quote",
      "news",
      "carousel_title",
      "carousel_body",
      "build_result",
      "cover",
    ]),
    aspect: z.enum(["9:16", "1:1", "4:5", "16:9"]),
    headline: short,
    source_ids: z.array(id).min(1).max(2),
    text: z.string().max(500),
    slides: z
      .array(z.object({ headline: short, body: z.string().max(500) }))
      .max(10)
      .default([]),
  }),
  z.object({ action: z.literal("graphics_process") }),
  z.object({
    action: z.literal("graphic_clear"),
    id,
    basis: text,
    scope: text,
    confirmed,
  }),
  z.object({
    action: z.literal("materialize_public"),
    id,
    kind: z.enum(["profile", "content", "build", "link"]),
    title: short,
    description: z.string().max(1000),
    body: z.string().max(12000),
    url: z
      .url()
      .regex(/^https:\/\//)
      .nullable(),
    confirmed,
  }),
  z.object({
    action: z.literal("link_create"),
    title: short,
    url: z.url().regex(/^https:\/\//),
    confirmed,
  }),
  z.object({
    action: z.literal("question_create"),
    text,
    source: short,
    consent: confirmed,
  }),
  z.object({ action: z.literal("job_retry"), id }),
  z.object({ action: z.literal("job_cancel"), id }),
]);
export type ControlCommand = z.infer<typeof controlCommand>;
